version: '3.9'
services:

  mongo:
    image: mongo:7
    container_name: mongo
    environment:
    - MONGO_INITDB_DATABASE=chatdb
    ports: 
      - "27018:27017"
    volumes:
      - mongo_db:/data/db 

  auth-service:
    env_file:
      - .env
    build:
      context: . 
      dockerfile: ./auth_service/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8001:8000"

  chat-service:
    env_file:
      - .env
    build:
      context: . 
      dockerfile: ./chat_service/Dockerfile    
    depends_on:
      - mongo
    ports:
      - "8002:8000"
    volumes:
      - ./chat_service:/app
      - ./shared:/app/shared
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  

volumes:
  mongo_db:
    
  